In [197]:
import pandas as pd
import matplotlib.pyplot as plt
import math
import numpy as np
from utils import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [187]:
readings = pd.read_pickle('/home/dlrc1/measurements/20180919T1541440000_ALL.pkl')

In [188]:
msmts = pd.DataFrame(readings)

In [189]:
msmts['lidar3'] = msmts['lidar_data'].apply(lambda x: x[3])

In [179]:
msmts[['lidar_timestamp', 'state_timestamp','lidar_fnumber', 'state_fnumber', 'lidar3', 'state_j_pos', 'calc_coordEE']]

KeyError: "['calc_coordEE'] not in index"

In [190]:
# get median / avg
print(msmts['lidar3'].mean())
print(msmts['lidar3'].median())
print(msmts['state_j_pos'][0])

407.72727272727275
423.0
[ 0.10540083 -0.36413842  0.08710472 -2.96334028  0.06907052  2.61860824
  1.71635902]


In [191]:
msmts.columns

Index(['lidar_data', 'lidar_fnumber', 'lidar_timestamp', 'state_c_ori_quat',
       'state_c_pos', 'state_c_vel', 'state_coriolis', 'state_dc_ori_quat',
       'state_flag_gripper', 'state_flag_ready', 'state_flag_real_robot',
       'state_fnumber', 'state_gravity', 'state_gripper_state', 'state_j_load',
       'state_j_pos', 'state_j_vel', 'state_last_cmd', 'state_mass',
       'state_ndofs', 'state_timestamp', 'systemtime', 'lidar3'],
      dtype='object')

In [199]:
Tproduct, Tlist, Tjoint, EE_coord = get_jointToCoordinates(msmts.iloc[10]['state_j_pos'].tolist(), trueCoordinates=None, untilJoint=10)

predicted coordinates [0.32822794 0.05652291 0.16140111 1.        ]
hey


In [173]:
msmts['calc_coordEE'] = msmts['state_j_pos'].apply(lambda x: get_jointToCoordinates(thetas=x, trueCoordinates=None, untilJoint=6)[3])

predicted coordinates [ 0.30738239 -0.0454091   0.13628985  1.        ]
predicted coordinates [ 0.30738153 -0.04540939  0.13628958  1.        ]
predicted coordinates [ 0.30738295 -0.04541024  0.13629097  1.        ]
predicted coordinates [ 0.30738215 -0.04540984  0.13629056  1.        ]
predicted coordinates [ 0.30738144 -0.045409    0.13628916  1.        ]
predicted coordinates [ 0.30738116 -0.04541099  0.13628963  1.        ]
predicted coordinates [ 0.30738205 -0.04541033  0.13628993  1.        ]
predicted coordinates [ 0.30738242 -0.04541048  0.13629055  1.        ]
predicted coordinates [ 0.30738213 -0.04540915  0.13628963  1.        ]
predicted coordinates [ 0.30738111 -0.04540944  0.13628923  1.        ]
predicted coordinates [ 0.30738123 -0.04540963  0.13628907  1.        ]
predicted coordinates [ 0.30738214 -0.04540919  0.13629047  1.        ]
predicted coordinates [ 0.30738231 -0.04540984  0.13629035  1.        ]
predicted coordinates [ 0.30738164 -0.04541134  0.13628972  1.  

predicted coordinates [ 0.30738093 -0.04540905  0.13628916  1.        ]
predicted coordinates [ 0.30738169 -0.04540895  0.13628958  1.        ]
predicted coordinates [ 0.30738208 -0.04541023  0.13629014  1.        ]
predicted coordinates [ 0.30738155 -0.04540992  0.13628896  1.        ]
predicted coordinates [ 0.30738111 -0.04540955  0.1362896   1.        ]
predicted coordinates [ 0.3073825  -0.04540899  0.13629034  1.        ]
predicted coordinates [ 0.30738174 -0.04540974  0.13628941  1.        ]
predicted coordinates [ 0.30738207 -0.04540994  0.13628987  1.        ]
predicted coordinates [ 0.30738267 -0.04541033  0.13629032  1.        ]
predicted coordinates [ 0.30738179 -0.04540995  0.1362896   1.        ]
predicted coordinates [ 0.30738121 -0.04540969  0.13628997  1.        ]
predicted coordinates [ 0.30738134 -0.04540939  0.13628944  1.        ]
predicted coordinates [ 0.30738153 -0.04540961  0.13628984  1.        ]
predicted coordinates [ 0.30738295 -0.04540989  0.13628974  1.  

predicted coordinates [ 0.3073804  -0.04540919  0.13628897  1.        ]
predicted coordinates [ 0.30738261 -0.0454105   0.13629074  1.        ]
predicted coordinates [ 0.30738289 -0.04540902  0.13628992  1.        ]
predicted coordinates [ 0.30738141 -0.04540977  0.13629003  1.        ]
predicted coordinates [ 0.30738179 -0.04540992  0.13628956  1.        ]
predicted coordinates [ 0.3073815  -0.0454106   0.13628989  1.        ]
predicted coordinates [ 0.3073824  -0.04541015  0.13629039  1.        ]
predicted coordinates [ 0.30738197 -0.04541005  0.13628955  1.        ]
predicted coordinates [ 0.30738192 -0.04540875  0.1362891   1.        ]
predicted coordinates [ 0.30738087 -0.04540969  0.13628911  1.        ]
predicted coordinates [ 0.30738172 -0.04540965  0.1362891   1.        ]
predicted coordinates [ 0.30738111 -0.04540997  0.13628943  1.        ]
predicted coordinates [ 0.30738162 -0.04540968  0.13628989  1.        ]
predicted coordinates [ 0.3073827  -0.04541048  0.13629031  1.  

predicted coordinates [ 0.3073814  -0.04540914  0.13628938  1.        ]
predicted coordinates [ 0.30738231 -0.0454102   0.13628939  1.        ]
predicted coordinates [ 0.30738113 -0.04540889  0.13628914  1.        ]
predicted coordinates [ 0.30738166 -0.04540962  0.13628931  1.        ]
predicted coordinates [ 0.30738255 -0.04540958  0.13629021  1.        ]
predicted coordinates [ 0.30738195 -0.04540904  0.13628933  1.        ]
predicted coordinates [ 0.30738055 -0.04540978  0.13628886  1.        ]
predicted coordinates [ 0.30738167 -0.04541059  0.13628993  1.        ]
predicted coordinates [ 0.30738215 -0.04540906  0.13628946  1.        ]
predicted coordinates [ 0.30738143 -0.04541007  0.13628969  1.        ]
predicted coordinates [ 0.30738192 -0.04541004  0.13628926  1.        ]
predicted coordinates [ 0.30738154 -0.04541026  0.13628931  1.        ]
predicted coordinates [ 0.30738124 -0.04540974  0.13628925  1.        ]
predicted coordinates [ 0.30738192 -0.04541031  0.13628972  1.  

In [170]:
get_jointToCoordinates(msmts.iloc[1]['state_j_pos'].tolist(), trueCoordinates=[0.306, -0.045, 0.135], untilJoint=10)[1]

predicted coordinates [ 0.30738153 -0.04540939  0.13628958  1.        ]
difference of  0.001933708589431602


[array([[ 0.99802553,  0.0628096 ,  0.        ,  0.        ],
        [-0.0628096 ,  0.99802553, -0.        , -0.        ],
        [-0.        ,  0.        ,  1.        ,  0.333     ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 9.40437123e-01, -3.39967672e-01,  0.00000000e+00,
          0.00000000e+00],
        [ 2.08170161e-17,  5.75851656e-17,  1.00000000e+00,
          0.00000000e+00],
        [-3.39967672e-01, -9.40437123e-01,  6.12323400e-17,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[ 9.97939718e-01,  6.41585535e-02,  0.00000000e+00,
          0.00000000e+00],
        [-3.92857836e-18,  6.11061840e-17, -1.00000000e+00,
         -3.16000000e-01],
        [-6.41585535e-02,  9.97939718e-01,  6.12323400e-17,
          1.93494194e-17],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[-6.21702217e-01,  7.83253697e-01,  0.0000

In [167]:
msmts.iloc[0]['state_last_cmd'] 

array([-0.03041842, -0.60213333, -0.13876958, -0.02620224, -0.01292521,
       -0.00574723, -0.00077126])

In [ ]:
#lidardata = pd.DataFrame(pd.read_pickle('/home/dlrc1/measurements/20180918T0846210000_LIDAR.pkl'))

In [ ]:
#lidardata

In [ ]:
#realsense = (pd.read_pickle('/home/dlrc1/measurements/20180918T1224100000_realsense.pkl'))

In [ ]:
#realsense